import type { Metadata } from "next";
import { NavigationMenu } from "@/components/menu/navigation"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = true
  const userRole = "admin" as const
  const userName = "Uziel Estrada"
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationMenu isAuthenticated={isAuthenticated} userRole={userRole} userName={userName} />
        {children}
      </body>
    </html>
  );
}
